export const MAIN_SCREEN = 'MEETING_SCREEN';

export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REG_SCREEN = 'REG_SCREEN';

export const MAIN_STACK = 'MAIN_STACK';
export const AUTHENTICATION_STACK = 'AUTHENTICATION_STACK';